apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-searchpv0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/open-search/data"
  claimRef:
    namespace: open-search
    name: opensearch-cluster-master-opensearch-cluster-master-0

