#!/bin/bash


kubectl exec -it -n open-search pods/opensearch-cluster-master-0 -- /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -backup /usr/share/opensearch/config/opensearch-security-backup -icl  -nhnv  -rev  -cacert /usr/share/opensearch/config/root-ca.pem  -cert /usr/share/opensearch/config/kirk.pem -key /usr/share/opensearch/config/kirk-key.pem

kubectl exec -it -n open-search pods/opensearch-cluster-master-0 -- /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/opensearch/config/opensearch-security-backup/ -rev  -cacert /usr/share/opensearch/config/root-ca.pem  -cert /usr/share/opensearch/config/kirk.pem -key /usr/share/opensearch/config/kirk-key.pem

kubectl cp open-search/opensearch-cluster-master-0:/usr/share/opensearch/config/opensearch-security-backup backup
