apiVersion: v2
name: opensearch-deployment
description: A Helm chart for deploying OpenSearch
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: opensearch
    version: "1.0.0"
    repository: "https://opensearch-project.github.io/helm-charts/"
